### PR TITLE
Update engines node to <=18.x.x

### PR DESCRIPTION
**Pull request by prokopsimek**
It works on my machine 💯

### CODE REVIEW

**Comment by hedenica** [comment]
This would be great! ;)

**Comment by leonardocustodio** [comment]
Can we get this merged? @GtaExFab

**Review by GtaExFab — APPROVED** [review]

**Comment by GtaExFab** [comment]
@prokopsimek, @hedenica, @leonardocustodio 
Merged and Thank you!

**Comment by BayBreezy** [comment]
Hello @GtaExFab . I am still having this issue with strapi v4.19.1.
When I try to install with yarn, I get this 
```bash
The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.19.0"
```

This is after running `yarn add strapi-plugin-email-designer@latest`

**Pull request merged**
